app/controllers/TrainingController.php
<?php
/**
 * Контроллер Тренировок по скорочтению
 */

namespace app\controllers;

use DateTime;


class TrainingController extends AppController
{
    public $layout = 'training';
    public $timeTraining;

    public function __construct($route) {

        parent::__construct($route);

        if ( !isset($_SESSION['user']) ) {

            redirect('/');

        }

        if ( isset($_SESSION['user']['access']) && $_SESSION['user']['access'] === 'no' ) {

            redirect('training/index');

        }

    }

    /**
     * В зависимости от возраста пользователя выбирается список упражнений для тренировки
     * @var $arrPractice array - массив со списком упражнений для тренировок
     * @return array - весь список упражнений для тренировки
     */
    protected function searchPractice() {

        $arrPractice = [
            [
                ['SCHULTETABLE','schulte'],
                ['SEARCHLETTERS','letter-search'],
                ['SEARCHDIGITAL','digital-search'],
                ['REMEMBERNUMBER','remember-number'],
                ['RUNWORDS','running-words'],
                ['SEARCHWORDS','word-search'],
                ['TWINWORDS','words-twins'],
                ['FIELDVIEW','field-view'],
                ['CHAINWORDS','chain-words'],
                ['READINGACCELERATOR','reading-accelerator'],
                ['TEXTSEARCH','text-search'],
                ['READINGGRADE','reading-grade'],
                ['STROOPTEST', 'stroop'],
                ['REMEMBERWORDS', 'remember-words']
            ],
            [
                ['SCHULTETABLE','schulte'],
                ['SEARCHLETTERS','letter-search'],
                ['SEARCHDIGITAL','digital-search'],
                ['EVENODD','even-odd'],
                ['REMEMBERNUMBER','remember-number'],
                ['RUNWORDS','running-words'],
                ['SEARCHWORDS','word-search'],
                ['TWINWORDS','words-twins'],
                ['FIELDVIEW','field-view'],
                ['CHAINWORDS','chain-words'],
                ['READINGACCELERATOR','reading-accelerator'],
                ['TEXTSEARCH','text-search'],
                ['READINGGRADE','reading-grade'],
                ['STROOPTEST', 'stroop'],
                ['REMEMBERWORDS', 'remember-words']
            ]
        ];
        /*$arrPractice = [
            [
                ['Таблица Шульте','schulte'],
                ['Поиск букв','letter-search'],
                ['Поиск цифр','digital-search'],
                ['Запомни число','remember-number'],
                ['Бегущие слова','running-words'],
                ['Поиск слова','word-search'],
                ['Слова близнецы','words-twins'],
                ['Поле зрения','field-view'],
                ['Цепь слов','chain-words'],
                ['Ускоритель чтения','reading-accelerator'],
                ['Поиск в тексте','text-search'],
                ['Оценка чтения','reading-grade'],
                ['Тест Струпа', 'stroop'],
                ['Запомни слова', 'remember-words']
            ],
            [
                ['Таблица Шульте','schulte'],
                ['Поиск букв','letter-search'],
                ['Поиск цифр','digital-search'],
                ['Чет/нечет','even-odd'],
                ['Запомни число','remember-number'],
                ['Бегущие слова','running-words'],
                ['Поиск слова','word-search'],
                ['Слова близнецы','words-twins'],
                ['Поле зрения','field-view'],
                ['Цепь слов','chain-words'],
                ['Ускоритель чтения','reading-accelerator'],
                ['Поиск в тексте','text-search'],
                ['Оценка чтения','reading-grade'],
                ['Тест Струпа', 'stroop'],
                ['Запомни слова', 'remember-words']
            ]
        ];*/

        if ($this->userAge < 10 && $this->userAge !== 0) {

            $listPractice = $arrPractice[0];

        } else {

            $listPractice = $arrPractice[1];

        }

        return $listPractice;
    }

    /**
     * Функция, в которой в зависти от вида тренировки устанавливается
     * продолжительность упражнений и записывается в свойство timeTraining
     */
    protected function currentTraining() {

        $training = $_GET['training'];

        switch ($training) {
            case 'speedy':
                $this->timeTraining = 60000;
                break;
            case 'periodic':
                $this->timeTraining = 90000;
                break;
            case 'optimal':
            case 'intense':
            $this->timeTraining = 150000;
                break;
        }
    }

    /**
     *
     */
    protected function replaceText($arrReplace) {

        $tmpArray = [];
        foreach ($arrReplace as $key => $item) {

            $tmpArray[$key][0] = $this->languageConstants[$item[0]];
            $tmpArray[$key][1] = $item[1];

        }

        return$tmpArray;

    }

    /**
     * Начальная страница тренировок
     */
    public function actionIndex() {

        $this->set(['languageConstants' => $this->languageConstants]);

    }

    /**
     * Тренировка "Быстрая"
     *
     * получается список упражнений для данного возраста
     * перемешивается и берутся первые 5 упражнений.
     * В файл передаётся массив упражнений для тренировки.
     */
    public function actionSpeedy() {

        $listPractice = $this->searchPractice();
        $listPractice = array_slice($listPractice, 0, -3);
        shuffle($listPractice);

        $currentListPractice = array_slice($listPractice, 0, 5);

        $currentListPractice = $this->replaceText($currentListPractice);

        $this->set(['currentListPractice' => $currentListPractice, 'languageConstants' => $this->languageConstants]);

    }

    /**
     * Тренировка "Периодическая"
     *
     * получаем список упражненийдля данного возраста
     * мешаем список и выбираем первые 7 упражнений
     * в файл передаёт массив упражнений для тренировки
     */
    public function actionPeriodic() {

        $listPractice = $this->searchPractice();
        $listPractice = array_slice($listPractice, 0, -3);
        shuffle($listPractice);

        $currentListPractice = array_slice($listPractice, 0, 7);

        $currentListPractice = $this->replaceText($currentListPractice);

        $this->set(['currentListPractice' => $currentListPractice, 'languageConstants' => $this->languageConstants]);

    }

    /**
     * Тренировка "Оптимальная"
     *
     * получаем список упражненийдля данного возраста
     * перемешиваем список и выбираем первые 12 упражнений
     * в файл передаёт массив упражнений для тренировки
     */
    public function actionOptimal() {

        $listPractice = $this->searchPractice();

        shuffle($listPractice);

        $currentListPractice = array_slice($listPractice, 0, 12);

        $currentListPractice = $this->replaceText($currentListPractice);

        $this->set(['currentListPractice' => $currentListPractice, 'languageConstants' => $this->languageConstants]);

    }

    /**
     * Тренировка "Интенсивная"
     *
     * получаем список упражненийдля данного возраста
     * делаем копию списка
     * перемешиваем оба списка и выбираем 24 упражнения
     * в файл передаёт массив упражнений для тренировки
     */
    public function actionIntense() {

        $tmpPractice = $this->searchPractice();
        $tmpPractice2 = $tmpPractice;
        shuffle($tmpPractice);
        shuffle($tmpPractice2);

        $listPractice = array_merge($tmpPractice, $tmpPractice2);

        $currentListPractice = array_slice($listPractice, 0, 24);

        $currentListPractice = $this->replaceText($currentListPractice);

        $this->set(['currentListPractice' => $currentListPractice, 'languageConstants' => $this->languageConstants]);

    }

    /**
     *
     */
    public function actionRememberWords() {
        $this->currentTraining();
        $this->set(['timePractice' => $this->timeTraining, 'languageConstants' => $this->languageConstants]);

    }

    /**
     *
     */
    public function actionDigitalSearch() {

        $this->currentTraining();
        $this->set(['timePractice' => $this->timeTraining, 'languageConstants' => $this->languageConstants]);

    }

    /**
     *
     */
    public function actionEvenOdd() {

        $this->currentTraining();
        $this->set(['timePractice' => $this->timeTraining, 'languageConstants' => $this->languageConstants]);

    }

    /**
     *
     */
    public function actionFieldView() {

        $this->currentTraining();
        $this->set(['timePractice' => $this->timeTraining, 'languageConstants' => $this->languageConstants]);

    }

    /**
     *
     */
    public function actionLetterSearch() {

        $this->currentTraining();
        $this->set(['timePractice' => $this->timeTraining, 'languageConstants' => $this->languageConstants]);

    }

    /**
     *
     */
    public function actionReadingAccelerator() {

        $titles = [];

        // в зависимости от возраста пользователя выбираем в библиотеке все файлы с текстами
        if ($this->userAge <= 9 && $this->userAge !== 0) {
            $listFiles = glob('data/' . $this->lang . '/lib/baby/*.xml');
            $numberPart = 4;
        } else {
            $listFiles = glob('data/' . $this->lang . '/lib/*.xml');
            $numberPart = 3;
        }

        // формируем массив с названиями текстов
        foreach ($listFiles as $currentFile) {
            $tmpStr = explode('/', $currentFile);
            $tmpStr = $tmpStr[$numberPart];
            $tmpStr = explode('.', $tmpStr, -1);
            $tmpStr = $tmpStr[0];
            $titles[] = $tmpStr;
        }

        $keyFile = 0;

        if (isset($_SESSION['user']['accelerator']) && $_SESSION['user']['accelerator'] !== '') {

            $keyFile = array_search($_SESSION['user']['accelerator'], $titles);

            $keyFile++;

            if ($keyFile === count($titles)) {

app/views/training/even-odd.php
<?php
/**
 * Упражнение Поиск букв
 *
 * @var $timePractice - integer время, отводимое на выполнение упражнения
 * @var $languageConstants
 */

?>

<main class="training-basic practice-page even-odd">
    <div class="setting-wrapper hidden-block" id="setting-wrapper">
        <p>
            <span id="setting-level"><?= (isset($_SESSION['user']['even_odd'])) ? $_SESSION['user']['even_odd'] : 1; ?></span>
            <span id="setting-time"><?= $timePractice; ?></span>
        </p>
    </div>
    <div class="timeline" id="timeline"></div>
    <div class="container">
        <div class="flex-block">
            <div class="start-btn-wrapper active" id="start-wrapper">
                <button class="btn orange-bg-light" onclick="clickStart();"><?= $languageConstants['START'] ?></button>
            </div>
            <div class="counter-start" id="counter-start">3</div>
            <div class="practice-wrapper flex-block">
                <div>
                    <h3 id="currentAction"><?= $languageConstants['FIND'] ?>:</h3>
                    <p id="currentElementClick"></p>
                </div>
                <table class="tbl-wrapper" id="tbl-wrapper">
                    <tbody></tbody>
                </table>
            </div>
            <div class="finish-practice flex-block" id="finish-practice">
                <h3><?= $languageConstants['EXERCISECOMPLETED'] ?></h3>
                <div>
                    <h4><?= $languageConstants['WORKOUTEFFICIENCY'] ?></h4>
                    <p class="result-practice"></p>
                </div>
                <div class="chart-wrapper">
                    <h4><?= $languageConstants['YOURPACEEXECUTION'] ?></h4>
                    <div class="ct-chart ct-minor-seventh"></div>
                </div>
                <div class="training-next">
                    <a href="" class="return-list"><?= $languageConstants['NEXTEXERCISE'] ?></a>
                </div>
            </div>
            <div class="current-level" id="current-level"></div>
        </div>
    </div>

</main>

<script src="/js/training/basic.js"></script>
<script src="/js/training/even-odd.js"></script>

app/views/training/field-view.php
<?php
/**
 * Упражнение Поиск слова
 *
 * @var $timePractice - integer время, отводимое на выполнение упражнения
 * @var $languageConstants
 */

?>

<main class="training-basic practice-page field-view">
    <div class="setting-wrapper hidden-block">
        <p>
            <span id="setting-level"><?= (isset($_SESSION['user']['digital_search'])) ? $_SESSION['user']['digital_search'] : 1; ?></span>
            <span id="setting-time"><?= $timePractice; ?></span>
        </p>
    </div>
    </div>
    <div class="timeline" id="timeline"></div>
    <div class="container">
        <div class="flex-block">
            <div class="start-btn-wrapper active" id="start-wrapper">
                <button class="btn orange-bg-light" onclick="clickStart();"><?= $languageConstants['START'] ?></button>
            </div>
            <div class="counter-start" id="counter-start">3</div>
            <div class="practice-wrapper field-view flex-block">
                <div class="flex-block">
                    <table class="info-block" id="info-block">
                        <tbody>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <table class="tbl-wrapper col-2" id="tbl-wrapper">
                    <tbody>
                    <tr>
                        <td data-value='0'><?= $languageConstants['NOTSAME'] ?></td>
                        <td data-value='1'><?= $languageConstants['SAME'] ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="finish-practice flex-block" id="finish-practice">
                <h3><?= $languageConstants['EXERCISECOMPLETED'] ?></h3>
                <div>
                    <h4><?= $languageConstants['TRAININGRESULT'] ?></h4>
                    <p class="result-practice"></p>
                    <p></p>
                </div>
                <div class="training-next">
                    <a href="" class="return-list"><?= $languageConstants['NEXTEXERCISE'] ?></a>
                </div>
            </div>
            <div class="current-level" id="current-level"></div>
        </div>
    </div>
</main>

<script src="/js/training/basic.js"></script>
<script src="/js/training/field-view.js"></script>

app/views/training/index.php
<?php
/**
 * Исходная страница выбора вида тренировки
 *
 * @var $languageConstants
 */

?>

<main class="training-page">
    <div class="container flex-block">
        <div class="training-index">
            <a href="training/speedy" class="btn orange-bg-light"><?= $languageConstants['FAST'] ?> (5 <?= $languageConstants['MINUTES'] ?>)</a>
            <a href="training/periodic" class="btn orange-bg-light"><?= $languageConstants['PERIODIC'] ?> (10 <?= $languageConstants['MINUTES'] ?>)</a>
            <a href="training/optimal" class="btn orange-bg-light"><?= $languageConstants['OPTIMAL'] ?> (30 <?= $languageConstants['MINUTES'] ?>)</a>
            <a href="training/intense" class="btn orange-bg-light"><?= $languageConstants['INTENCE'] ?> (60 <?= $languageConstants['MINUTES'] ?>)</a>
        </div>
    </div>
</main>

app/views/training/intense.php
<?php
/**
 * Индексный файл Интенсивной тренировки
 *
 * @var $currentListPractice
 * @var $languageConstants
 */

?>

<main class="training-page">
    <div class="container flex-block">
        <div class="training-index intense">
            <h4 class="orange-text-dark"><?= $languageConstants['PRACTICEDEXERCISES'] ?></h4>
            <ul class="flex-block">
                <?php foreach ($currentListPractice as $item) : ?>
                    <li class="<?= $item[1] ?>"><?= $item[0] ?></li>
                <?php endforeach; ?>
            </ul>
            <a href="/training/<?= $currentListPractice[0][1] ?>?training=intense&number=1" class="btn orange-bg-light"><?= $languageConstants['START'] ?></a>
        </div>
    </div>
</main>

<script>
    var tmp = JSON.stringify(<?= json_encode($currentListPractice) ?>);
    sessionStorage.setItem('intense', tmp);
</script>

app/views/training/letter-search.php
<?php
/**
 * Упражнение Поиск букв
 *
 * @var $timePractice - integer время, отводимое на выполнение упражнения
 * @var $languageConstants
 */

?>

<main class="training-basic practice-page letter-search">
    <div class="setting-wrapper hidden-block">
        <p>
            <span id="setting-level"><?= (isset($_SESSION['user']['letter_search'])) ? $_SESSION['user']['letter_search'] : 1; ?></span>
            <span id="setting-time"><?= $timePractice; ?></span>
        </p>
    </div>
    <div class="timeline" id="timeline"></div>
    <div class="container">
        <div class="flex-block">
            <div class="start-btn-wrapper active" id="start-wrapper">
                <button class="btn orange-bg-light" onclick="clickStart();"><?= $languageConstants['START'] ?></button>
            </div>
            <div class="counter-start" id="counter-start">3</div>
            <div class="practice-wrapper flex-block">
                <div>
                    <h3 id="currentAction"><?= $languageConstants['FIND'] ?>:</h3>
                    <p id="currentElementClick"></p>
                </div>
                <table class="tbl-wrapper" id="tbl-wrapper">
                    <tbody></tbody>
                </table>
            </div>
            <div class="finish-practice flex-block" id="finish-practice">
                <h3><?= $languageConstants['EXERCISECOMPLETED'] ?></h3>
                <div>
                    <h4><?= $languageConstants['WORKOUTEFFICIENCY'] ?></h4>
                    <p class="result-practice"></p>
                </div>
                <div class="chart-wrapper">
                    <h4><?= $languageConstants['YOURPACEEXECUTION'] ?></h4>
                    <div class="ct-chart ct-minor-seventh"></div>
                </div>
                <div class="training-next">
                    <a href="" class="return-list"><?= $languageConstants['NEXTEXERCISE'] ?></a>
                </div>
            </div>
            <div class="current-level" id="current-level"></div>
        </div>
    </div>
</main>

<script src="/js/training/basic.js"></script>
<script src="/js/training/letter-search.js"></script>

app/views/training/optimal.php
<?php
/**
 * Индексный файл "Тренировки Оптимальная"
 *
 * @var $currentListPractice
 * @var $languageConstants
 */

?>

<main class="training-page">
    <div class="container flex-block">
        <div class="training-index">
            <h4 class="orange-text-dark"><?= $languageConstants['PRACTICEDEXERCISES'] ?></h4>
            <ul>
                <?php foreach ($currentListPractice as $item) : ?>
                    <li class="<?= $item[1] ?>"><?= $item[0] ?></li>
                <?php endforeach; ?>
            </ul>

            <a href="/training/<?= $currentListPractice[0][1] ?>?training=optimal&number=1" class="btn orange-bg-light"><?= $languageConstants['START'] ?></a>

        </div>
    </div>
</main>

<script>
    var tmp = JSON.stringify(<?= json_encode($currentListPractice) ?>);
    sessionStorage.setItem('optimal', tmp);
</script>

app/views/training/periodic.php
<?php
/**
 * Индексный файл "Тренировка Периодическая"
 *
 * @var $currentListPractice
 * @var $languageConstants
 */

?>

<main class="training-page">
    <div class="container flex-block">
        <div class="training-index">
            <h4 class="orange-text-dark"><?= $languageConstants['PRACTICEDEXERCISES'] ?></h4>
            <ul>
                <?php foreach ($currentListPractice as $item) : ?>
                    <li class="<?= $item[1] ?>"><?= $item[0] ?></li>
                <?php endforeach; ?>
            </ul>
                        <a href="/training/<?= $currentListPractice[0][1] ?>?training=periodic&number=1" class="btn orange-bg-light"><?= $languageConstants['START'] ?></a>
        </div>
    </div>
</main>

<script>
    var tmp = JSON.stringify(<?= json_encode($currentListPractice) ?>);
    sessionStorage.setItem('periodic', tmp);
</script>

app/views/training/reading-accelerator.php
<?php
/**
 * Упражнение Оценка чтения
 *
 * @var $titles
 * @var $dataText
 * @var $languageConstants
 */

$text = "";

foreach ((array)$dataText->text->p as $value) {
    $text .= "<p>$value</p>";
}

$arrSpeedText = [50, 60, 70, 80, 90, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000];

if (isset($_SESSION['user']['speed_grade'])) {
    $currentUserSpeed = $_SESSION['user']['speed_grade'];
} else {
    $currentUserSpeed = 50;
}

foreach ($arrSpeedText as $value) {
    if ($currentUserSpeed > $value) {
        $newSpeed = $value;
    } else {
        $newSpeed = $value;
        break;
    }
}
?>

<main class="training-basic practice-page accelerator">
    <div class="setting-wrapper hidden-block">
        <p>
            <span id="setting-title"><?= $dataText->title ?></span>
            <span id="setting-speed"><?= $newSpeed ?></span>
        </p>
    </div>
    <div class="container">
        <div class="flex-block">
            <div class="start-btn-wrapper active" id="start-wrapper">
                <button class="btn orange-bg-light" onclick="clickStart();"><?= $languageConstants['START'] ?></button>
            </div>
            <div class="counter-start" id="counter-start"></div>
            <div class="practice-wrapper accelerator">
                <div class="info-block" id="info-block">
                    <div data-words="<?= $dataText->words?>">
                        <?= $text ?>
                    </div>

                    <div class="curtain"></div>
                </div>
            </div>
            <div class="finish-practice flex-block" id="finish-practice">
                <h3><?= $languageConstants['EXERCISECOMPLETED'] ?></h3>
                <div class="training-next">
                    <a href="" class="return-list"><?= $languageConstants['NEXTEXERCISE'] ?></a>
                </div>
            </div>
        </div>
    </div>
</main>

<script src="/js/training/reading-accelerator.js"></script>

app/views/training/reading-grade.php
<?php
/**
 * Упражнение Оценка чтения
 *
 * @var $titles
 * @var $dataText
 * @var $languageConstants
 */

$text = "";

foreach ((array)$dataText->text->p as $value) {
    $text .= "<p>$value</p>";
}

$questions = $dataText->questions->question_body;
shuffle($questions);
$questions = array_slice($questions, 0, 5);

?>

<main class="training-basic practice-page reading-grade">
    <div class="setting-wrapper hidden-block">
        <p>
            <span id="setting-title"><?= $dataText->title ?></span>
        </p>
    </div>
    <div class="container">
        <div class="flex-block">
            <div class="start-btn-wrapper active" id="start-wrapper">
                <button class="btn orange-bg-light" onclick="clickStart();"><?= $languageConstants['START'] ?></button>
            </div>
            <div class="counter-start" id="counter-start"></div>
            <div class="practice-wrapper reading-grade">
                <div id="info-block">
                    <div>
                        <?= $text ?>
                    </div>
                </div>
                <div class="btn-body">
                    <button class="btn orange-bg-light" onclick="nextText();"><?= $languageConstants['FARTHER'] ?></button>
                </div>
            </div>
            <div class="control-block" id="control-block">
                <ul>
                    <?php
                    $i = 0;
                    foreach ($questions as $item) :

                        ?>
                    <li>
                        <p class="orange-text-dark"><?= $languageConstants['QUESTION'] ?> <?= $i + 1 ?> <?= $languageConstants['FROM'] ?> 5</p>
                        <h4><?= $item->question ?></h4>
                        <div>
                        <?php
                        $successAnswer = $item->answers->answer[0];
                        $arrTmp = $item->answers->answer;
                        shuffle($arrTmp);

                        foreach ($arrTmp as $value) {
                        ?>
                            <button class="btn" data-answer="<?= $successAnswer ?>" data-number="<?= $i + 1 ?>" onclick="answerClick(this)"><?= $value ?></button>
                        <?php } ?>
                        </div>

                    </li>
                    <?php $i++; endforeach; ?>
                </ul>
            </div>
            <div class="finish-practice flex-block" id="finish-practice">
                <h3><?= $languageConstants['EXERCISECOMPLETED'] ?></h3>
                <div class="result-reading" id="result-reading">
                    <h4><?= $languageConstants['READSPEED'] ?>:<br><span data-countwords="<?= $dataText->words ?>"></span> <?= $languageConstants['WORDSMIN'] ?>.</h4>
                    <p><?= $languageConstants['CORRECTANSWERS'] ?> <span></span> <?= $languageConstants['FROM'] ?> 5 (<span></span>%)</p>
                    <p></p>
                </div>
                <div class="training-next">
                    <a href="" class="return-list"><?= $languageConstants['NEXTEXERCISE'] ?></a>
                </div>
            </div>
        </div>
    </div>
</main>

<script src="/js/training/reading-grade.js"></script>

app/views/training/speedy.php
<?php
/**
 * Индексный файл тренировки "Быстрая"
 *
 * На каждое упражнение отводится по 1 минуте
 * После окончания упражнения, к очередному переход осуществляется по ссылке в конце упражнения
 * В SessionStorage сохряняется упражнения и порядок их следования
 *
 * @var $currentListPractice - массив с упражнениями для отработки
 * @var $languageConstants
 */

?>

<main class="training-page">
    <div class="container flex-block">
        <div class="training-index">
            <h4 class="orange-text-dark"><?= $languageConstants['PRACTICEDEXERCISES'] ?></h4>
            <ul>
                <?php foreach ($currentListPractice as $item) : ?>
                <li class="<?= $item[1] ?>"><?= $item[0] ?></li>
                <?php endforeach; ?>
            </ul>

            <a href="/training/remember-words?training=speedy&number=1" class="btn orange-bg-light"><?= $languageConstants['START'] ?></a>
        </div>
    </div>
</main>

<script>
    var tmp = JSON.stringify(<?= json_encode($currentListPractice) ?>);
    sessionStorage.setItem('speedy', tmp);
</script>