app/controllers/PracticeController.php
<?php
/**
 *
 */

namespace app\controllers;

use app\models\User;

class PracticeController extends AppController
{
    public function __construct($route) {

        parent::__construct($route);

        if ( !isset($_SESSION['user']) ) {

            redirect('/');

        }

        if ( isset($_SESSION['user']['access']) && $_SESSION['user']['access'] === 'no' ) {

            redirect('practice/index');

        }

    }

    public $layout = 'training';

    public function actionIndex() {

        $this->set(['languageConstants' => $this->languageConstants]);

    }

    /**
     * Упражнение "Таблица Шульте"
     */
    public function actionSchulte()
    {
        $infoPractice = file_get_contents("data/" . $this->lang . '/info/schulte.txt');

        if ($_POST) {

            if (isset($_POST['alphabet'])) {

                // получение алфавита, согласно используемого языка
                $alphabet = file_get_contents('data/' . $this->lang . '/alf.txt');

                echo $alphabet;

                exit();
            }

            if (isset($_POST['level'])) {

                if ($_SESSION['user']['role'] == 'pupil') {

                    $this->rememberLevel('schulte');

                    if (!$_SESSION['user']['birthday']) {

                        echo 0;

                    } else {

                        echo $this->userAge;

                    }

                } else {

                    echo true;

                }

                exit();
            }
        }

        $this->set(['languageConstants' => $this->languageConstants, 'infoPractice' => $infoPractice]);
    }

    /**
     * Упражнение "Поиск букв"
     */
    public function actionLetterSearch()
    {

        $infoPractice = file_get_contents("data/" . $this->lang . '/info/letter-search.txt');
        $coupleFile = parse_ini_file('data/' . $this->lang . '/couple.ini');
        $couple = [];

        foreach ($coupleFile as $item) {

            $elem = explode(':', $item);
            $couple[] = $elem[0];

        }

        if ($_POST) {

            if (isset($_POST['alphabet'])) {

                $letters = file_get_contents('data/' . $this->lang . '/alf.txt');

                echo $letters;

                exit();

            }

            if (isset($_POST['couple'])) {

                $coupleFile = parse_ini_file('data/' . $this->lang . '/couple.ini');
                $arrCouple = explode(':', $coupleFile[$_POST['couple']]);
                $arrCouple = $arrCouple[1];

                echo $arrCouple;

                exit();

            }

            if (isset($_POST['level'])) {

                if ($_SESSION['user']['role'] == 'pupil') {

                    $this->rememberLevel('letter_search');

                    echo 'level = ' . $_POST['level'];

                } else {

                    echo true;

                }

                exit();
            }
        }

        $this->set(['couple' => $couple, 'languageConstants' => $this->languageConstants, 'infoPractice' => $infoPractice]);

    }

    /**
     * Упражнение "Поиск цифр"
     */
    public function actionDigitalSearch()
    {

        $infoPractice = file_get_contents("data/" . $this->lang . '/info/digital-search.txt');

        if ($_POST) {


            if (isset($_POST['level'])) {

                if ($_SESSION['user']['role'] == 'pupil') {

                    $this->rememberLevel('digital_search');

                    echo 'level = ' . $_POST['level'];

                } else {

                    echo true;

                }

                exit();
            }
        }

        $this->set(['languageConstants' => $this->languageConstants, 'infoPractice' => $infoPractice]);

    }

    /**
     * Упражнение "Чет/нечет"
     */
    public function actionEvenOdd()
    {

        $infoPractice = file_get_contents("data/" . $this->lang . '/info/even-odd.txt');

        if ($_POST) {

            if (isset($_POST['level'])) {

                if ($_SESSION['user']['role'] == 'pupil') {

                    $this->rememberLevel('even_odd');

                    echo 'level = ' . $_POST['level'];

                } else {

                    echo true;

                }

                exit();
            }
        }

        $this->set(['languageConstants' => $this->languageConstants, 'infoPractice' => $infoPractice]);

    }

    /**
     * Упражнение "Запомни число"
     */
    public function actionRememberNumber()
    {

        $infoPractice = file_get_contents("data/" . $this->lang . '/info/remember-number.txt');

        if ($_POST) {

            if (isset($_POST['level'])) {

                if ($_SESSION['user']['role'] == 'pupil') {

                    $this->rememberLevel('rem_number');

                    echo 'level = ' . $_POST['level'];

                } else {

                    echo true;

                }

                exit();
            }
        }

        $this->set(['languageConstants' => $this->languageConstants, 'infoPractice' => $infoPractice]);

    }

    /**
     * Упражнение"Бегущие слова"
     */
    public function actionRunningWords()
    {

        $infoPractice = file_get_contents("data/" . $this->lang . '/info/running-words.txt');

        if ($_POST) {

            if (isset($_POST['words'])) {

                $words = file_get_contents('data/' . $this->lang . '/words-run.txt');

                $letters = parse_ini_file('data/' . $this->lang . '/alf-width.ini');

                $data = [
                    'words' => $words,
                    'letters' => $letters,
                ];

                echo json_encode($data);

                exit();

            }


            if (isset($_POST['level'])) {

                if ($_SESSION['user']['role'] == 'pupil') {

                    $this->rememberLevel('run_words');

                    echo 'level = ' . $_POST['level'];

                } else {

                    echo true;

                }

                exit();
            }
        }

        $this->set(['languageConstants' => $this->languageConstants, 'infoPractice' => $infoPractice]);

    }

    /**
     *  Упражнение "Поиск слова"
     */
    public function actionWordSearch()
    {

        $infoPractice = file_get_contents("data/" . $this->lang . '/info/word-search.txt');
        $coupleFile = parse_ini_file('data/' . $this->lang . '/couple-words.ini');
        $couple = [];

        foreach ($coupleFile as $item) {

            $elem = explode(':', $item);
            $couple[] = $elem[0];

        }

        if ($_POST) {

            if (isset($_POST['words'])) {

                $words = file_get_contents('data/' . $this->lang . '/word-search.txt');

                $letters = parse_ini_file('data/' . $this->lang . '/alf-width.ini');

                $letters = array_keys($letters);

                $data = [
                    'words' => $words,
                    'letters' => $letters,
                ];

                echo json_encode($data);

                exit();

            }

            if (isset($_POST['couple'])) {

                $coupleFile = parse_ini_file('data/' . $this->lang . '/couple-words.ini');
                $arrCouple = explode(':', $coupleFile[$_POST['couple']]);
                $arrCouple = $arrCouple[1];

                echo $arrCouple;

                exit();

            }

            if (isset($_POST['level'])) {

                if ($_SESSION['user']['role'] == 'pupil') {

                    $this->rememberLevel('word_search');

                    echo 'level = ' . $_POST['level'];

                } else {

                    echo true;

                }

                exit();
            }
        }

        $this->set(['couple' => $couple, 'languageConstants' => $this->languageConstants, 'infoPractice' => $infoPractice]);

    }

    /**
     * Упражнение "Слова Близнецы"
     */
    public function actionWordsTwins()
    {
        $infoPractice = file_get_contents("data/" . $this->lang . '/info/words-twins.txt');

        if ($_POST) {

            if (isset($_POST['words'])) {

                $handle = fopen('data/' . $this->lang . '/word-twins.csv', 'r');
                $words = fgetcsv($handle, 0, ',');
                fclose($handle);
                $data = [];
                foreach ($words as $key => $item) {
                    $data[$key] = explode('-', $item);
                }

                echo json_encode($data);

                exit();

            }

            if (isset($_POST['level'])) {

                if ($_SESSION['user']['role'] == 'pupil') {

                    $this->rememberLevel('words_twins');

                    echo 'level = ' . $_POST['level'];

                } else {

                    echo true;

                }

                exit();
            }
        }

        $this->set(['languageConstants' => $this->languageConstants, 'infoPractice' => $infoPractice]);

    }

    /**
     * Упражнение "Поле зрения"
     */
    public function actionFieldView()
    {

        $infoPractice = file_get_contents("data/" . $this->lang . '/info/fields-view.txt');

        if ($_POST) {

            if (isset($_POST['letters'])) {

                $letters = parse_ini_file('data/' . $this->lang . '/alf-width.ini');

                $letters = array_keys($letters);

                echo json_encode($letters);

                exit();

            }

            if (isset($_POST['level'])) {

                if ($_SESSION['user']['role'] == 'pupil') {

                    $this->rememberLevel('field_view');

                    echo 'level = ' . $_POST['level'];

                } else {

                    echo true;

                }

                exit();
            }
        }

        $this->set(['languageConstants' => $this->languageConstants, 'infoPractice' => $infoPractice]);

    }

    /**

app/views/practice/central-point.php
<?php
/**
 * Упражнение Поиск слова
 *
 * @var $languageConstants array
 * @var $infoPractice string
 */

?>

<main class="training-basic practice-page center-point">
    <div class="setting-wrapper">
        <form action="" id="setting-form">
            <label class="lbl-setting-time"  for="setting-time"></label>
            <select name="setting-time" id="setting-time">
                <option value="300000">5 мин.</option>
                <option value="420000" selected>7 мин.</option>
                <option value="600000">10 мин.</option>
                <option value="900000">15 мин.</option>
            </select>
            <button type="button" class="practice-info" onclick="openPracticeInfo()"></button>
        </form>
    </div>
    <div class="container">
        <div class="flex-block">
            <div class="start-btn-wrapper active" id="start-wrapper">
                <button class="btn orange-bg-light" onclick="clickStart();"><?= $languageConstants['START'] ?></button>
            </div>
            <div class="counter-start" id="counter-start"></div>
            <div class="practice-wrapper central-point flex-block">
                <div id="info-block"></div>
            </div>
            <div class="finish-practice flex-block" id="finish-practice">
                <h3><?= $languageConstants['EXERCISECOMPLETED'] ?></h3>
                <div>
                    <a href="/practice" class="return-list"><?= $languageConstants['TOLISTEXERCISES'] ?></a>
                </div>
            </div>
        </div>
    </div>
    <section class="practice-info-wrapper flex-block" id="practice-info-wrapper">
        <div class="container">
            <h3 class="orange-text-dark">Центральная точка</h3>
            <div><?= $infoPractice ?></div>
            <button onclick="closePracticeInfo()"><?= $languageConstants['ALLCLEAR'] ?></button>
        </div>
    </section>
</main>

<script src="/js/practice/basic.js"></script>
<script src="/js/practice/central-point.js"></script>

app/views/practice/chain-words.php
<?php
/**
 * Упражнение Цепь слов
 *
 * @var $languageConstants array
 * @var $infoPractice string
 */

?>

<main class="training-basic practice-page remember-words">
    <div class="setting-wrapper">
        <form action="" id="setting-form">
            <label class="lbl-setting-time"  for="setting-time"></label>
            <select name="setting-time" id="setting-time">
                <option value="3000" >3 сек.</option>
                <option value="5000" >5 сек.</option>
                <option value="7000">7 сек.</option>
                <option value="10000" selected>10 сек.</option>
                <option value="15000">15 сек.</option>
                <option value="20000">20 сек.</option>
                <option value="25000">25 сек.</option>
                <option value="30000">30 сек.</option>
                <option value="35000">35 сек.</option>
                <option value="40000">40 сек.</option>
                <option value="45000">45 сек.</option>
                <option value="50000">50 сек.</option>
                <option value="55000">55 сек.</option>
                <option value="60000">60 сек.</option>
            </select>
            <label class="lbl-setting-level" for="setting-level"></label>
            <select name="setting-level" id="setting-level">
                <option value="1" >10 <?= $languageConstants['WORDS'] ?></option>
                <option value="2" >20 <?= $languageConstants['WORDS'] ?></option>
                <option value="3" >30 <?= $languageConstants['WORDS'] ?></option>
                <option value="4" >40 <?= $languageConstants['WORDS'] ?></option>
                <option value="5" >50 <?= $languageConstants['WORDS'] ?></option>
            </select>
            <button type="button" class="practice-info" onclick="openPracticeInfo()"></button>
        </form>
    </div>
    <div class="timeline" id="timeline"></div>
    <div class="container">
        <div class="flex-block">
            <div class="start-btn-wrapper active" id="start-wrapper">
                <button class="btn orange-bg-light" onclick="clickStart();"><?= $languageConstants['START'] ?></button>
            </div>
            <div class="counter-start" id="counter-start">3</div>
            <div class="practice-wrapper remember-words flex-block">
                <div class="flex-block">
                    <div class="info-block" id="info-block"></div>
                    <ul class="control-block"></ul>
                </div>
                <ul class="tbl-wrapper" id="tbl-wrapper"></ul>
            </div>
            <div class="finish-practice flex-block" id="finish-practice">
                <h3><?= $languageConstants['EXERCISECOMPLETED'] ?></h3>
                <div>
                    <h4><?= $languageConstants['TRAININGRESULT'] ?></h4>
                    <p class="result-practice"></p>
                    <h4><?= $languageConstants['ANSWERSPENT'] ?></h4>
                    <p class="time-answer"></p>
                </div>
                <div>
                    <button class="btn orange-bg-light repeat" onclick="repeatPractice();"><?= $languageConstants['REPEAT'] ?></button>
                    <a href="/practice" class="return-list"><?= $languageConstants['TOLISTEXERCISES'] ?></a>
                </div>
            </div>
            <div class="current-level" id="current-level"></div>
        </div>
    </div>
    <section class="practice-info-wrapper flex-block" id="practice-info-wrapper">
        <div class="container">
            <h3 class="orange-text-dark">Цепь слов</h3>
            <div><?= $infoPractice ?></div>
            <button onclick="closePracticeInfo()"><?= $languageConstants['ALLCLEAR'] ?></button>
        </div>
    </section>
</main>

<script src="/js/practice/basic.js"></script>
<script src="/js/practice/chain-words.js"></script>

app/views/practice/digital-search.php
<?php
/**
 * Упражнение Поиск цифр
 *
 * @var $languageConstants array
 * @var $infoPractice string
 */

?>

<main class="training-basic practice-page letter-search">
    <div class="setting-wrapper">
        <form action="" id="setting-form">
            <label class="lbl-setting-time"  for="setting-time"></label>
            <select name="setting-time" id="setting-time">
                <option value="30000">0.5 мин.</option>
                <option value="60000" selected>1 мин.</option>
                <option value="90000">1.5 мин.</option>
                <option value="120000">2 мин.</option>
                <option value="180000">3 мин.</option>
                <option value="300000">5 мин.</option>
                <option value="300000">7 мин.</option>
                <option value="300000">10 мин.</option>
                <option value="300000">15 мин.</option>
            </select>
            <label class="lbl-setting-level" for="setting-level"></label>
            <select name="setting-level" id="setting-level">
                <option value="1" <?= ((isset($_SESSION['user']['digital_search']) && $_SESSION['user']['digital_search'] == NULL) || !isset($_SESSION['user']['digital_search']) ) ? 'selected' : ''; ?>>1</option>
                <option value="2" <?= (isset($_SESSION['user']['digital_search']) && ($_SESSION['user']['digital_search'] == 2)) ? 'selected' : ''; ?>>2</option>
                <option value="3" <?= (isset($_SESSION['user']['digital_search']) && ($_SESSION['user']['digital_search'] == 3)) ? 'selected' : ''; ?>>3</option>
                <option value="4" <?= (isset($_SESSION['user']['digital_search']) && ($_SESSION['user']['digital_search'] == 4)) ? 'selected' : ''; ?>>4</option>
                <option value="5" <?= (isset($_SESSION['user']['digital_search']) && ($_SESSION['user']['digital_search'] == 5)) ? 'selected' : ''; ?>>5</option>
                <option value="6" <?= (isset($_SESSION['user']['digital_search']) && ($_SESSION['user']['digital_search'] == 6)) ? 'selected' : ''; ?>>6</option>
                <option value="7" <?= (isset($_SESSION['user']['digital_search']) && ($_SESSION['user']['digital_search'] == 7)) ? 'selected' : ''; ?>>7</option>
                <option value="8" <?= (isset($_SESSION['user']['digital_search']) && ($_SESSION['user']['digital_search'] == 8)) ? 'selected' : ''; ?>>8</option>
            </select>
            <button type="button" class="practice-info" onclick="openPracticeInfo()"></button>
        </form>
    </div>
    <div class="timeline" id="timeline"></div>
    <div class="container">
        <div class="flex-block">
            <div class="start-btn-wrapper active" id="start-wrapper">
                <button class="btn orange-bg-light" onclick="clickStart();"><?= $languageConstants['START'] ?></button>
            </div>
            <div class="counter-start" id="counter-start">3</div>
            <div class="practice-wrapper flex-block">
                <div>
                    <h3 id="currentAction"><?= $languageConstants['FIND'] ?>:</h3>
                    <p id="currentElementClick"></p>
                </div>
                <table class="tbl-wrapper" id="tbl-wrapper">
                    <tbody></tbody>
                </table>
            </div>
            <div class="finish-practice flex-block" id="finish-practice">
                <h3><?= $languageConstants['EXERCISECOMPLETED'] ?></h3>
                <div>
                    <h4><?= $languageConstants['WORKOUTEFFICIENCY'] ?></h4>
                    <p class="result-practice"></p>
                </div>
                <div class="chart-wrapper">
                    <h4><?= $languageConstants['YOURPACEEXECUTION'] ?></h4>
                    <div class="ct-chart ct-minor-seventh"></div>
                </div>
                <div>
                    <button class="btn orange-bg-light repeat" onclick="repeatPractice();"><?= $languageConstants['REPEAT'] ?></button>
                    <a href="/practice" class="return-list"><?= $languageConstants['TOLISTEXERCISES'] ?></a>
                </div>
            </div>
            <div class="current-level" id="current-level"></div>
        </div>
    </div>
    <section class="practice-info-wrapper flex-block" id="practice-info-wrapper">
        <div class="container">
            <h3 class="orange-text-dark">Поиск числа</h3>
            <div><?= $infoPractice ?></div>
            <button onclick="closePracticeInfo()"><?= $languageConstants['ALLCLEAR'] ?></button>
        </div>
    </section>
</main>

<script src="/js/practice/basic.js"></script>
<script src="/js/practice/digital-search.js"></script>

app/views/practice/even-odd.php
<?php
/**
 * Упражнение "Чет/нечет"
 *
 * @var $languageConstants array
 * @var $infoPractice string
 */

?>

<main class="training-basic practice-page even-odd">
    <div class="setting-wrapper">
        <form action="" id="setting-form">
            <label class="lbl-setting-time"  for="setting-time"></label>
            <select name="setting-time" id="setting-time">
                <option value="30000">0.5 мин.</option>
                <option value="60000" selected>1 мин.</option>
                <option value="90000">1.5 мин.</option>
                <option value="120000">2 мин.</option>
                <option value="180000">3 мин.</option>
                <option value="300000">5 мин.</option>
                <option value="300000">7 мин.</option>
                <option value="300000">10 мин.</option>
                <option value="300000">15 мин.</option>
            </select>
            <label class="lbl-setting-level" for="setting-level"></label>
            <select name="setting-level" id="setting-level">
                <option value="1" <?= ((isset($_SESSION['user']['even_odd']) && $_SESSION['user']['even_odd'] == NULL) || !isset($_SESSION['user']['even_odd']) ) ? 'selected' : ''; ?>>1</option>
                <option value="2" <?= (isset($_SESSION['user']['even_odd']) && ($_SESSION['user']['even_odd'] == 2)) ? 'selected' : ''; ?>>2</option>
                <option value="3" <?= (isset($_SESSION['user']['even_odd']) && ($_SESSION['user']['even_odd'] == 3)) ? 'selected' : ''; ?>>3</option>
                <option value="4" <?= (isset($_SESSION['user']['even_odd']) && ($_SESSION['user']['even_odd'] == 4)) ? 'selected' : ''; ?>>4</option>
                <option value="5" <?= (isset($_SESSION['user']['even_odd']) && ($_SESSION['user']['even_odd'] == 5)) ? 'selected' : ''; ?>>5</option>
                <option value="6" <?= (isset($_SESSION['user']['even_odd']) && ($_SESSION['user']['even_odd'] == 6)) ? 'selected' : ''; ?>>6</option>
                <option value="7" <?= (isset($_SESSION['user']['even_odd']) && ($_SESSION['user']['even_odd'] == 7)) ? 'selected' : ''; ?>>7</option>
                <option value="8" <?= (isset($_SESSION['user']['even_odd']) && ($_SESSION['user']['even_odd'] == 8)) ? 'selected' : ''; ?>>8</option>
            </select>
            <button type="button" class="practice-info" onclick="openPracticeInfo()"></button>
        </form>
    </div>
    <div class="timeline" id="timeline"></div>
    <div class="container">
        <div class="flex-block">
            <div class="start-btn-wrapper active" id="start-wrapper">
                <button class="btn orange-bg-light" onclick="clickStart();"><?= $languageConstants['START'] ?></button>
            </div>
            <div class="counter-start" id="counter-start">3</div>
            <div class="practice-wrapper flex-block">
                <div>
                    <h3 id="currentAction"><?= $languageConstants['FIND'] ?>:</h3>
                    <p id="currentElementClick"></p>
                </div>
                <table class="tbl-wrapper" id="tbl-wrapper">
                    <tbody></tbody>
                </table>
            </div>
            <div class="finish-practice flex-block" id="finish-practice">
                <h3><?= $languageConstants['EXERCISECOMPLETED'] ?></h3>
                <div>
                    <h4><?= $languageConstants['WORKOUTEFFICIENCY'] ?></h4>
                    <p class="result-practice"></p>
                </div>
                <div class="chart-wrapper">
                    <h4><?= $languageConstants['YOURPACEEXECUTION'] ?></h4>
                    <div class="ct-chart ct-minor-seventh"></div>
                </div>
                <div>
                    <button class="btn orange-bg-light repeat" onclick="repeatPractice();"><?= $languageConstants['REPEAT'] ?></button>
                    <a href="/practice" class="return-list"><?= $languageConstants['TOLISTEXERCISES'] ?></a>
                </div>
            </div>
            <div class="current-level" id="current-level"></div>
        </div>
    </div>
    <section class="practice-info-wrapper flex-block" id="practice-info-wrapper">
        <div class="container">
            <h3 class="orange-text-dark">Чет/Нечет</h3>
            <div><?= $infoPractice ?></div>
            <button onclick="closePracticeInfo()"><?= $languageConstants['ALLCLEAR'] ?></button>
        </div>
    </section>
</main>

<script src="/js/practice/basic.js"></script>
<script src="/js/practice/even-odd.js"></script>

app/views/practice/gen-text.php
<?php
/**
 *
 */

$homepage = file_get_contents('upload/text.txt');

$homepage = str_replace(PHP_EOL, ' ', $homepage);

$homepage = str_replace(['.', ',', ':', '«', '»'], '', $homepage);
//$homepage = str_replace(',', '', $homepage);
//$homepage = str_replace(',', '', $homepage);

$arrWords = explode(' ', $homepage);

$arr = [];
foreach ( $arrWords as $item) {
    $item= mb_strtolower($item, 'UTF-8');
    if (iconv_strlen($item) > 3) {
        if (strpos($item, '-') === false) {
            $arr[] = $item;
        }
    }
}
$arrNewWords = array_unique($arr);

$recordFile = fopen('upload/words-old.txt', 'a');
foreach ($arrNewWords as $item) {
    fwrite($recordFile, $item . "\r\n");
}
fclose($recordFile);

app/views/practice/index.php
<?php
/**
 * Страница выбора упражнения
 *
 * @var $languageConstants
 */

?>

<main class="practice-page practice-index no-fixed-page">
    <div class="container">
        <div class="flex-block">
            <a href="practice/schulte" class="btn orange-bg-light schulte"><?= $languageConstants['SCHULTETABLE'] ?></a>
            <a href="practice/letter-search" class="btn orange-bg-light search-letter"><?= $languageConstants['SEARCHLETTERS'] ?></a>
            <a href="practice/digital-search" class="btn orange-bg-light search-digit"><?= $languageConstants['SEARCHDIGITAL'] ?></a>
            <a href="practice/even-odd" class="btn orange-bg-light even-odd"><?= $languageConstants['EVENODD'] ?></a>
            <a href="practice/remember-number" class="btn orange-bg-light remember-number"><?= $languageConstants['REMEMBERNUMBER'] ?></a>
            <a href="practice/running-words" class="btn orange-bg-light running-words"><?= $languageConstants['RUNWORDS'] ?></a>
            <a href="practice/word-search" class="btn orange-bg-light word-search"><?= $languageConstants['SEARCHWORDS'] ?></a>
            <a href="practice/words-twins" class="btn orange-bg-light words-twins"><?= $languageConstants['TWINWORDS'] ?></a>
            <a href="practice/field-view" class="btn orange-bg-light field-view"><?= $languageConstants['FIELDVIEW'] ?></a>
            <a href="practice/central-point" class="btn orange-bg-light central-point"><?= $languageConstants['CENTREDOT'] ?></a>
            <a href="practice/remember-words" class="btn orange-bg-light remember-words"><?= $languageConstants['REMEMBERWORDS'] ?></a>
            <a href="practice/chain-words" class="btn orange-bg-light chain-words"><?= $languageConstants['CHAINWORDS'] ?></a>
            <a href="practice/reading-grade" class="btn orange-bg-light reading-grade"><?= $languageConstants['READINGGRADE'] ?></a>
            <a href="practice/reading-accelerator" class="btn orange-bg-light reading-accelerator"><?= $languageConstants['READINGACCELERATOR'] ?></a>
            <a href="practice/text-search" class="btn orange-bg-light text-search"><?= $languageConstants['TEXTSEARCH'] ?></a>
            <a href="practice/stroop" class="btn orange-bg-light stroop"><?= $languageConstants['STROOPTEST'] ?></a>
        </div>
    </div>
</main>

app/views/practice/stroop.php
<?php
/**
 * Упражнение Бегущие слова
 *
 * @var $languageConstants array
 * @var $infoPractice string
 */

?>

<main class="training-basic practice-page stroop">
    <div class="setting-wrapper">
        <form action="" id="setting-form">
            <label class="lbl-setting-color" for="setting-color"></label>
            <select name="setting-color" id="setting-color">
                <option value="3">3 <?= $languageConstants['COLOR'] ?></option>
                <option value="4">4 <?= $languageConstants['COLOR'] ?></option>
                <option value="5">5 <?= $languageConstants['COLORS'] ?></option>
            </select>
            <button type="button" class="practice-info" onclick="openPracticeInfo()"></button>
        </form>
    </div>
    <div class="timeline" id="timeline"></div>
    <div class="container">
        <div class="flex-block">
            <div class="start-btn-wrapper active" id="start-wrapper">
                <button class="btn orange-bg-light" onclick="clickStart();"><?= $languageConstants['START'] ?></button>
            </div>
            <div class="counter-start" id="counter-start">3</div>
            <div class="practice-wrapper stroop" id="practice-wrapper">
                <ul>
                    <li class="card-1" id="card-1">
                        <table class="stroop-card"><tbody></tbody></table>
                        <hr>
                        <table class="tbl-wrapper" id="btn-card1"><tbody></tbody></table>
                    </li>
                    <li class="card-2" id="card-2">
                        <table class="stroop-card"><tbody></tbody></table>
                        <hr>
                        <table class="tbl-wrapper" id="btn-card2"><tbody></tbody></table>
                    </li>
                    <li class="card-3" id="card-3">
                        <table class="stroop-card"><tbody></tbody></table>
                        <hr>
                        <table class="tbl-wrapper" id="btn-card3"><tbody></tbody></table>
                    </li>
                </ul>
            </div>
            <div class="finish-practice flex-block" id="finish-practice">
                <h3><?= $languageConstants['EXERCISECOMPLETED'] ?></h3>
                <div>
                    <h4><?= $languageConstants['TRAININGRESULT'] ?></h4>
                    <h5><?= $languageConstants['CARDNO1'] ?></h5>
                    <p class="result-practice"></p>
                    <h5><?= $languageConstants['CARDNO2'] ?></h5>
                    <p class="result-practice"></p>
                    <h5><?= $languageConstants['CARDNO3'] ?></h5>
                    <p class="result-practice"></p>
                </div>
                <div>
                    <a href="/practice" class="return-list"><?= $languageConstants['TOLISTEXERCISES'] ?></a>
                </div>
            </div>
            <div class="current-level" id="current-level"></div>
        </div>
    </div>
    <section class="practice-info-wrapper flex-block" id="practice-info-wrapper">
        <div class="container">
            <h3 class="orange-text-dark">Тест Струпа</h3>
            <div><?= $infoPractice ?></div>
            <button onclick="closePracticeInfo()"><?= $languageConstants['ALLCLEAR'] ?></button>
        </div>
    </section>
</main>

<script src="/js/practice/basic.js"></script>
<script src="/js/practice/stroop.js"></script>